### ISSUE TITLE
WFS

### ISSUE THREAD

**Issue by stevage** [tmcw-up-for-adoption/lonlat#2]
Expected to see the WFS order change appear here:

http://docs.geoserver.org/latest/en/user/services/wfs/basics.html

> WFS 1.0.0 servers return geographic coordinates in longitude/latitude (x/y) order, the most common way to distribute data. For example, most shapefiles adopt this order by default.

>However, the traditional axis order for geographic and cartographic systems is the opposite—latitude/longitude (y/x)—and the later WFS specifications respect this. The default axis ordering support is:

>Latitude/longitude—WFS 1.1.0 and WFS 2.0.0
>Longitude/latitude—WFS 1.0.0

**Comment by tmcw** [comment]
Thanks for the note - it seems like there would need to be an additional note about yet another exception - when WFS returns GML, which it does often, then the coordinate order is decided by the projection. I guess this'll be a big footnote.
